# Generated by Django 5.0.6 on 2024-08-05 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.CharField(choices=[('F', 'Float'), ('T', 'Text')], default='T', max_length=1)),
                ('value', models.TextField()),
            ],
        ),
    ]
